import CryptoKit
import Foundation
import Testing
@testable import SuperAgent

/// CryptoKit must produce byte-identical output to the Mac's node:crypto. The
/// vectors were generated by the desktop test; if either side changes, both fail.
struct CryptoTests {
    struct Vectors: Decodable {
        var machineId: String
        var secretHex: String
        var keyM2pHex: String
        var keyP2mHex: String
        var saltHex: String
        var plaintext: String
        var frameM2p: String
        var pairingCode: String
    }
    private final class Marker {}

    private func vectors() throws -> Vectors {
        let url = try #require(Bundle(for: Marker.self).url(forResource: "crypto-vectors", withExtension: "json"))
        return try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
    }

    @Test func derivesTheSameKeysAsTheMac() throws {
        let v = try vectors()
        let keys = DeviceKeys(secret: Data(hex: v.secretHex)!, machineId: v.machineId)
        #expect(keys.m2p.withUnsafeBytes { Data($0).hex } == v.keyM2pHex)
        #expect(keys.p2m.withUnsafeBytes { Data($0).hex } == v.keyP2mHex)
    }

    @Test func opensAFrameTheMacSealed() throws {
        let v = try vectors()
        let keys = DeviceKeys(secret: Data(hex: v.secretHex)!, machineId: v.machineId)
        var opener = Opener(key: keys.m2p, aad: aad(machineId: v.machineId, direction: .m2p))
        #expect(opener.open(v.frameM2p) == v.plaintext)
        // Replay is refused.
        #expect(opener.open(v.frameM2p) == nil)
    }

    @Test func sealsExactlyWhatTheMacWouldWithTheSameSalt() throws {
        let v = try vectors()
        let keys = DeviceKeys(secret: Data(hex: v.secretHex)!, machineId: v.machineId)
        var sealer = Sealer(key: keys.m2p, aad: aad(machineId: v.machineId, direction: .m2p), salt: Data(hex: v.saltHex)!)
        #expect(try sealer.seal(v.plaintext) == v.frameM2p)
    }

    @Test func roundTripsAndRejectsWrongDirection() throws {
        let secret = Data((0..<32).map { _ in UInt8.random(in: 0...255) })
        let m = String(repeating: "cd", count: 32)
        let keys = DeviceKeys(secret: secret, machineId: m)
        var s = Sealer(key: keys.p2m, aad: aad(machineId: m, direction: .p2m))
        var o = Opener(key: keys.p2m, aad: aad(machineId: m, direction: .p2m))
        let f1 = try s.seal("one"), f2 = try s.seal("two")
        #expect(o.open(f1) == "one")
        #expect(o.open(f2) == "two")
        #expect(o.open(f1) == nil)
        var wrong = Opener(key: keys.m2p, aad: aad(machineId: m, direction: .m2p))
        #expect(wrong.open(try s.seal("three")) == nil)
    }

    @Test func pairingCodeMatchesTheMac() throws {
        let v = try vectors()
        #expect(pairingCode(secret: Data(hex: v.secretHex)!, machineId: v.machineId) == v.pairingCode)
    }
}

extension Data {
    init?(hex: String) {
        guard hex.count % 2 == 0 else { return nil }
        var out = Data(capacity: hex.count / 2)
        var i = hex.startIndex
        while i < hex.endIndex {
            let j = hex.index(i, offsetBy: 2)
            guard let b = UInt8(hex[i..<j], radix: 16) else { return nil }
            out.append(b)
            i = j
        }
        self = out
    }
    var hex: String { map { String(format: "%02x", $0) }.joined() }
}
